# image used for the healthcheck binary
FROM golang:1.17beta1-buster  AS build
WORKDIR /go/src/healthcheck/

COPY healthcheck.go .
COPY go.mod .
COPY go.sum .

RUN GOOS=linux GOARCH=amd64 go build -ldflags '-w -s' -o /healthcheck /go/src/healthcheck/

FROM debian:buster-slim
COPY --from=build /healthcheck /healthcheck
