# image used for the healthcheck binary
FROM golang:1.16.5-alpine3.13 AS build
WORKDIR /go/src/healthcheck/

COPY healthcheck.go .
COPY go.mod .
COPY go.sum .

RUN GOOS=linux GOARCH=amd64 go build -ldflags '-w -s' -o /healthcheck /go/src/healthcheck/

FROM alpine:3.14.0
COPY --from=build /healthcheck /healthcheck
